CREATE OR REPLACE TYPE TYPE_EMPLOYEE UNDER ROW_EMPLOYEE
( -- object oriented ROWTYPE for EMPLOYEES table
  -- $Revision: 8696 $
  -- created : 2007-08-24 15:04:03

  -- attributes
    JOB_TITLE       VARCHAR2(35)
	, DEPARTMENT_NAME VARCHAR2(30)

  -- define constructors 
  , CONSTRUCTOR FUNCTION TYPE_EMPLOYEE RETURN SELF AS RESULT
  , CONSTRUCTOR FUNCTION TYPE_EMPLOYEE(IN_EMPLOYEE_ID NUMBER) RETURN SELF AS RESULT

  -- define member functions 
	, MEMBER FUNCTION GET_MANAGER RETURN TYPE_EMPLOYEE
) NOT FINAL
/
CREATE OR REPLACE TYPE BODY TYPE_EMPLOYEE IS
-- $Revision: 8696 $

  -- constructors
  CONSTRUCTOR FUNCTION TYPE_EMPLOYEE RETURN SELF AS RESULT
  IS
  BEGIN

    SELF.OBJECT_TYPE_NAME  := 'TYPE_EMPLOYEE';
    SELF.ROW_DEFAULT();
    RETURN;

  END;

  ---------------------------------------------------------------

  CONSTRUCTOR FUNCTION TYPE_EMPLOYEE(IN_EMPLOYEE_ID NUMBER) RETURN SELF AS RESULT
  IS
  BEGIN

    SELF.OBJECT_TYPE_NAME  := 'HR.TYPE_EMPLOYEE';
    SELF.ROW_SELECT(IN_EMPLOYEE_ID => IN_EMPLOYEE_ID);

		SELF.JOB_TITLE        := ROW_JOB(IN_JOB_ID => SELF.JOB_ID).JOB_TITLE;
		SELF.DEPARTMENT_NAME  := ROW_DEPARTMENT(IN_DEPARTMENT_ID => SELF.DEPARTMENT_ID).DEPARTMENT_NAME;

    RETURN;

  END;

  ---------------------------------------------------------------

  MEMBER FUNCTION GET_MANAGER RETURN TYPE_EMPLOYEE
  IS
  BEGIN

    RETURN TYPE_EMPLOYEE(IN_EMPLOYEE_ID => SELF.MANAGER_ID);

  END;

END;
/
